//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seafood_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int id { get; set; }
        public int quatity { get; set; }
        public int productdetailsID { get; set; }
        public int orderID { get; set; }
        public double price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Productdetail Productdetail { get; set; }
    }
}
