//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seafood_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int id { get; set; }
        public System.DateTime orderdate { get; set; }
        public string deliveryAddress { get; set; }
        public string payment { get; set; }
        public decimal Total { get; set; }
        public string status { get; set; }
        public int cartID { get; set; }
        public int userID { get; set; }
        public string paymentMethod { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<double> fee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual User User { get; set; }
    }
}
